pipeline{
    // Node with label Slave1 will be used to execute the pipeline on
    agent {
        label "Slave1"
    }

    stages{
        stage("Greet"){
            steps{
                echo "Hello World, I'm Learning Jenkins"
            }
        }
    }
}